min_ios_version_supported = '13.4'

require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  # Commenting this out if not needed
  # use_frameworks! :linkage => linkage.to_sym
end

use_modular_headers!

target 'Kinga' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'KingaTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    puts "Running React Native post-install hook"
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
